//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancoSucursal
    {
        public int Id { get; set; }
        public int IdBanco { get; set; }
        public int SucursalNro { get; set; }
        public string Sucursal { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public Nullable<int> IdBarrio { get; set; }
        public string Direccion { get; set; }
        public string Web { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
    }
}
