//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Domicilios()
        {
            this.Proveedores = new HashSet<Proveedores>();
        }
    
        public int Id { get; set; }
        public int IdBarrio { get; set; }
        public int IdLocalidad { get; set; }
        public int IdDepartamento { get; set; }
        public int IdProvincia { get; set; }
    
        public virtual Barrios Barrios { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual Provincias Provincias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proveedores> Proveedores { get; set; }
    }
}
