//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EArticulos
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public string CodBarra { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdRubro { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public decimal CostoInicial { get; set; }
        public decimal CostoAdicional1 { get; set; }
        public decimal CostoAdicional2 { get; set; }
        public decimal Costo { get; set; }
        public Nullable<int> Stock { get; set; }
        public int StockMinimo { get; set; }
        public Nullable<decimal> PrecioL1 { get; set; }
        public Nullable<decimal> PrecioL2 { get; set; }
        public Nullable<decimal> PrecioL3 { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual EMarcas EMarcas { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual ERubros ERubros { get; set; }
        public virtual Unidades Unidades { get; set; }
    }
}
