//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EComprasDetalles
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<int> IdCompra { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual ECompras ECompras { get; set; }
        public virtual EArticulos EArticulos { get; set; }
    }
}
