//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECompras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ECompras()
        {
            this.EComprasDetalles = new HashSet<EComprasDetalles>();
        }
    
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> Retirado { get; set; }
        public Nullable<int> Pagado { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EComprasDetalles> EComprasDetalles { get; set; }
    }
}
