//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECuentas
    {
        public int Id { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idReferencia { get; set; }
        public Nullable<decimal> SaldoInicial { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
