//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDepositos
    {
        public int Id { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Deposito { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public Nullable<int> idBarrio { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> idEncargado { get; set; }
    }
}
