//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMovimientos
    {
        public int Id { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idVenta { get; set; }
        public Nullable<int> idCompra { get; set; }
        public Nullable<int> idNotaCredito { get; set; }
        public Nullable<int> idNotaDebito { get; set; }
        public Nullable<int> idCheque { get; set; }
        public Nullable<int> idCuenta { get; set; }
        public string Detalle { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public Nullable<decimal> Debito { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Contrasiento { get; set; }
    }
}
