//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMovimStock
    {
        public int Id { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idArticulo { get; set; }
        public Nullable<int> idProveedorOrigen { get; set; }
        public Nullable<int> idClienteOrigen { get; set; }
        public Nullable<int> idDepositoOrigen { get; set; }
        public Nullable<int> idProveedorDestino { get; set; }
        public Nullable<int> idClienteDestino { get; set; }
        public Nullable<int> idDepositoDestino { get; set; }
        public Nullable<decimal> Ingreo { get; set; }
        public Nullable<decimal> Egreso { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<int> Usuario { get; set; }
    }
}
