//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPresupuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EPresupuestos()
        {
            this.EPresupuestosDetalles = new HashSet<EPresupuestosDetalles>();
        }
    
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> DiasValidez { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> DescuentoPorc { get; set; }
        public Nullable<decimal> ImporteTotal { get; set; }
        public Nullable<int> PrecioLista { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPresupuestosDetalles> EPresupuestosDetalles { get; set; }
    }
}
