//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERemitos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERemitos()
        {
            this.ERemitosDetalles = new HashSet<ERemitosDetalles>();
        }
    
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdVenta { get; set; }
        public string EntregaNombre { get; set; }
        public string RecibeNombre { get; set; }
        public Nullable<int> RecibeTipoDocumento { get; set; }
        public Nullable<decimal> RecibeNroDocumento { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual EVentas EVentas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERemitosDetalles> ERemitosDetalles { get; set; }
    }
}
