//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barrios> Barrios { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<ComprasProductos> ComprasProductos { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Domicilios> Domicilios { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<GruposItemsMenu> GruposItemsMenu { get; set; }
        public virtual DbSet<GruposUsuarios> GruposUsuarios { get; set; }
        public virtual DbSet<ItemsMenu> ItemsMenu { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<MovimientosDinero> MovimientosDinero { get; set; }
        public virtual DbSet<MovimientosStock> MovimientosStock { get; set; }
        public virtual DbSet<OrigenMovimiento> OrigenMovimiento { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Remitos> Remitos { get; set; }
        public virtual DbSet<RemitosProductos> RemitosProductos { get; set; }
        public virtual DbSet<Rubros> Rubros { get; set; }
        public virtual DbSet<SubRubro> SubRubro { get; set; }
        public virtual DbSet<TiposDocumento> TiposDocumento { get; set; }
        public virtual DbSet<Unidad> Unidad { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosItemsMenu> UsuariosItemsMenu { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<VentasProductos> VentasProductos { get; set; }
        public virtual DbSet<TipoOperacion> TipoOperacion { get; set; }
    }
}
