//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosStock
    {
        public int Id { get; set; }
        public int IdProducto { get; set; }
        public int IdTipoOperacion { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Usuario { get; set; }
        public int Ingreso { get; set; }
        public int Egreso { get; set; }
        public int Stock { get; set; }
    }
}
