//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosDinero
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdCuenta { get; set; }
        public string Detalle { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public Nullable<decimal> Débito { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<int> Contrasiento { get; set; }
        public int IdOrigenMovimiento { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual OrigenMovimiento OrigenMovimiento { get; set; }
    }
}
