//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemitosProductos
    {
        public int Id { get; set; }
        public int IdRemito { get; set; }
        public int IdProducto { get; set; }
        public int IdUnidad { get; set; }
        public string Cantidad { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Remitos Remitos { get; set; }
        public virtual Unidad Unidad { get; set; }
    }
}
