//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursales
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdBanco { get; set; }
        public string Sucursal { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> IdDomicilio { get; set; }
        public string Direccion { get; set; }
        public string EMail { get; set; }
        public string Telefono { get; set; }
        public string Web { get; set; }
        public byte Estado { get; set; }
    
        public virtual Bancos Bancos { get; set; }
    }
}
